config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'route_constraints'

Rails.application.routes.draw do
  default_url_options Settings.default_url_options.symbolize_keys

  concern :archivable do
    member do
      delete :archive
      post :restore
    end
  end

  put :switch_locale, to: 'welcome#switch_locale'
  resource :super_user, only: %i[new create]

  scope subdomain: '', constraints: { subdomain: '' } do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development? || Rails.env.staging?
    get '/sidekiq-stats' => proc { [200, { 'Content-Type' => 'text/plain' }, [Sidekiq::Stats.new.to_json]] }
    Sidekiq::Web.set :session_secret, Rails.application.credentials.secret_key_base
    mount Sidekiq::Web => '/sidekiq' # , constraints: RouteConstraints::AdminRequiredConstraint.new

    root to: 'welcome#index'
    get :developers, to: 'pages#developers'
    resources :invites, only: [] do
      member do
        get :accept
      end
    end
    resources :sessions, only: %i[new create] do
      collection do
        delete :destroy
      end
    end
    resources :users, only: %i[new create]
    resource :profile, only: %i[show update], controller: :profile
    resources :password_resets, only: %i[new create edit update]
    resources :account_memberships, only: %i[destroy new create]

    resources :boards, except: %i[show index]
    resources :accounts

    resources :cards, only: %i[show edit update] do
      concerns :archivable
    end
    resources :invites, controller: :account_invites
    resources :board_memberships, only: [:destroy]
    resources :boards, only: %i[show edit update] do
      member do
        get :users
      end
      concerns :archivable
      resources :members, controller: :board_members
    end
  end

  scope '/api' do
    mount RootAPI => '/'
    root controller: :swagger, action: :index, as: :api_doc # , constraints: { format: :html }
  end

  match '*anything', to: 'application#not_found', via: %i[get post], constraints: { format: :html }
end

app/controllers/board_members_controller.rb
# frozen_string_literal: true

class BoardMembersController < ApplicationController
  layout false

  helper_method :board

  def new
    render locals: { form: InviteForm.new, invited: board.invites.ordered }
  end

  # rubocop:disable Metrics/AbcSize
  def create
    form = InviteForm.new params.require(:invite_form).permit(:emails)
    if form.valid?
      BatchInviteJob.perform_later(
        account_id: board.account_id,
        board_id: board.id,
        inviter_id: current_user.id,
        emails: form.emails_list
      )
      flash_notice! :invited, count: form.emails_list.count
      redirect_to board_path(board)
    else
      render :new, locals: { form: form, invited: board.invites.ordered }
    end
  end
  # rubocop:enable Metrics/AbcSize

  def index
    render locals: { members: board.members, invited: board.invites.ordered }, layout: 'simple'
  end

  private

  def board
    current_user.available_boards.find params[:board_id]
  end
end

app/helpers/board_members_helper.rb
# frozen_string_literal: true

module BoardMembersHelper
end

app/views/board_members/_form.slim
= simple_form_for form, url: board_members_path(board) do |f|
  = f.input :emails, as: :text, autofocus: true, input_html: { rows: 5, autosize: true }
  .row.mt-3
    .col-md-6
      = f.button :submit, class: 'btn btn-success'

app/views/board_members/index.html.slim
h2= t('.title', title: board.title)
h3= t '.members'

table.table.table-condensed.table-stripped.table-narrow
  tbody
    - members.each_with_index do |member, index|
      tr
        th= index+1
        td= member.name


= render 'invite_form', form: InviteForm.new, url: board_members_path(board)

- if invites.any?
  h3= t '.invited'
  table.table.table-condensed.table-stripped.table-narrow
    tbody
      - invites.each_with_index do |invite, index|
        tr
          th= index+1
          td= invite.email

app/views/board_members/new.html.slim
= simple_form_for form, url: board_members_url(board), remote: true, data: { type: :html } do |f|
  .modal-header
    h5#modalTitle.modal-title
      = t '.title'
    = render 'modal_close_button'

  .modal-body
      = f.error_notification
      = f.input :board, as: :string, input_html: { value: board.public_name }, disabled: true, hint: false
      = f.input :emails, as: :text, autofocus: true, input_html: { rows: 5, autosize: true }

      - if invited.any?
        = render 'invited', invites: invited

  .modal-footer
    = f.button :submit, class: 'btn-primary', data: { enableWhenChanged: true, disable_with: t('helpers.disable_with') }