config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'route_constraints'

Rails.application.routes.draw do
  default_url_options Settings.default_url_options.symbolize_keys

  concern :archivable do
    member do
      delete :archive
      post :restore
    end
  end

  put :switch_locale, to: 'welcome#switch_locale'
  resource :super_user, only: %i[new create]

  scope subdomain: '', constraints: { subdomain: '' } do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development? || Rails.env.staging?
    get '/sidekiq-stats' => proc { [200, { 'Content-Type' => 'text/plain' }, [Sidekiq::Stats.new.to_json]] }
    Sidekiq::Web.set :session_secret, Rails.application.credentials.secret_key_base
    mount Sidekiq::Web => '/sidekiq' # , constraints: RouteConstraints::AdminRequiredConstraint.new

    root to: 'welcome#index'
    get :developers, to: 'pages#developers'
    resources :invites, only: [] do
      member do
        get :accept
      end
    end
    resources :sessions, only: %i[new create] do
      collection do
        delete :destroy
      end
    end
    resources :users, only: %i[new create]
    resource :profile, only: %i[show update], controller: :profile
    resources :password_resets, only: %i[new create edit update]
    resources :account_memberships, only: %i[destroy new create]

    resources :boards, except: %i[show index]
    resources :accounts

    resources :cards, only: %i[show edit update] do
      concerns :archivable
    end
    resources :invites, controller: :account_invites
    resources :board_memberships, only: [:destroy]
    resources :boards, only: %i[show edit update] do
      member do
        get :users
      end
      concerns :archivable
      resources :members, controller: :board_members
    end
  end

  scope '/api' do
    mount RootAPI => '/'
    root controller: :swagger, action: :index, as: :api_doc # , constraints: { format: :html }
  end

  match '*anything', to: 'application#not_found', via: %i[get post], constraints: { format: :html }
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  include Sortable.new parent_id: :lane_id
  include Archivable

  belongs_to :board, touch: true
  belongs_to :lane, touch: true
  belongs_to :task

  has_one :account, through: :board
  has_one :author, through: :task

  has_many :comments, through: :task
  # TODO: Move membership to task
  has_many :memberships, class_name: 'CardMembership', dependent: :delete_all
  has_many :account_memberships, through: :memberships
  has_many :members, through: :account_memberships
  has_many :task_users, through: :task

  scope :open, -> { alive }

  before_validation do
    self.board_id ||= lane.try(:board_id)
  end

  def watchers
    members
  end

  delegate :number, :title, :details, :formatted_details, :comments_count, :attachments_count, :tags, to: :task
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def show
    edit
  end

  def edit
    TaskSeen.new(card.task, current_user).mark_as_seen! Time.zone.now
    render :edit,
           locals: { card: card },
           layout: request.xhr? ? false : 'card'
  end

  def update
    card.task.update! permitted_params
    BoardChannel.update_lanes card.board
    redirect_to board_path(card.board), notice: t_flash
  end

  def archive
    card.archive!
    # TODO: Update card's modal
    BoardChannel.update_lanes card.board.reload
    redirect_to board_path(card.board), notice: t_flash
  end

  private

  def card
    @card ||= current_user.available_cards.find params[:id]
  end

  def permitted_params
    params.require(:card).permit(:title, :details)
  end
end

app/views/cards/_sidebar.slim
div= user_name_with_avatar card.author
small.mt-1.text-muted= l card.task.created_at, format: :short
hr.mt-5

ul.list-unstyled
  li
    - if request.xhr?
      = link_to t('.fullscreen'), card_path(card), class: 'btn btn-sm btn-wide btn-outline-secondary'
    - else
      = link_to t('.fullscreen'), card_path(card), class: 'btn btn-sm btn-wide btn-secondary'

  li.mt-2= link_to t('helpers.buttons.archive'), archive_card_path(card), method: :delete, class: 'btn btn-sm btn-wide btn-outline-secondary'
  li.mt-2
    = react_component 'FileUpload', taskId: card.task_id

app/views/cards/edit.html.slim
div[style="position: relative"]
  - if request.xhr?
    = button_tag type: :button, class: 'icon-link icon-lg dialog-close-button close', 'aria-label': 'Close', data: { dismiss: :modal, 'card-modal-close': true } do
      = icon 'md-close'
  - else
    = link_to board_path(card.board), class: 'icon-link icon-lg dialog-close-button', data: { 'card-modal-close': true } do
      = icon 'md-close'
  header.card-dialog-header
    .row
      .col-md-1
        div.mt-1.text-muted[style='font-size: 24px']= icon 'md-card'
      .col-md-10
        h2.card-dialog-title
          = inline_card_title card, tabindex: 1

  section.mt-2
    .row
      .col-md-10
        .row.mt-3
          .col-md-1
            div.text-muted[style='font-size: 24px']= icon 'md-list'
          .col-md-9
            h4.text-muted.card-dialog-subtitle= t '.details'
            = inline_card_details card, tabindex: 2
        .row.mt-4
          .col-md-1
            div.text-muted[style='font-size: 24px']= icon 'md-people'
          .col-md-9
            h4.text-muted.card-dialog-subtitle= t '.members'
            .mt-3= card_members_selector card
        = task_attachments card.task
        .row.mt-4
          .col-md-1
            div.text-muted[style='font-size: 24px']= icon 'md-chatboxes'
          .col-md-9
            h4.text-muted.card-dialog-subtitle= t '.comments'
        .row
          .col-md-12.mt-2
            = task_comments_block card.task
      .col-md-2
        = render 'sidebar', card: card